// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {IERC20} from "./interfaces/IERC20.sol";
import {Ownable} from "./utils/Ownable.sol";

/**
 * @title EthVault
 * @notice Escrow for ERC20 tokens on the EVM side of a cross-chain channel.
 *         Supports ETH→SOL (lock) and SOL→ETH reverse (unlock).
 *         Each transfer has a timeout: if not committed within deadline, sender can reclaim.
 *
 * State machine per transfer:
 *   locked → committed (success) | refunded (timeout)
 */
contract EthVault is Ownable {
    struct LockRecord {
        address sender;
        address token;
        uint256 amount;
        uint256 timeoutAt;   // unix timestamp
        bool    committed;
        bool    refunded;
    }

    address public relayer;
    mapping(bytes32 => LockRecord) public locks;  // crossChainId => record

    event TokenLocked(
        address indexed sender,
        address indexed token,
        uint256 amount,
        bytes32 crossChainId,
        bytes32 nonceHash,
        bytes   destWallet,     // Solana pubkey as 32 bytes
        uint256 timeoutAt
    );
    event TransferCommitted(bytes32 indexed crossChainId);
    event TransferRefunded(bytes32 indexed crossChainId, address indexed sender, uint256 amount);
    event RelayerUpdated(address oldRelayer, address newRelayer);

    error AlreadyLocked(bytes32 crossChainId);
    error NotLocked(bytes32 crossChainId);
    error AlreadyFinalized(bytes32 crossChainId);
    error NotTimedOut(bytes32 crossChainId);
    error NotRelayer(address caller);
    error ZeroAmount();
    error ZeroAddress();
    error TransferFailed();

    modifier onlyRelayer() {
        if (msg.sender != relayer && msg.sender != owner) revert NotRelayer(msg.sender);
        _;
    }

    constructor(address _relayer) {
        if (_relayer == address(0)) revert ZeroAddress();
        relayer = _relayer;
    }

    // ── Lock ──────────────────────────────────────────────────────────────────

    /**
     * @notice Lock ERC20 tokens to initiate ETH→SOL transfer.
     * @param token        ERC20 contract address
     * @param amount       Token amount (in token's decimals)
     * @param crossChainId Unique identifier generated by hub (bytes32)
     * @param destWallet   Destination Solana wallet as 32-byte pubkey
     * @param timeoutSec   Seconds until this lock expires and can be refunded
     */
    function lock(
        address token,
        uint256 amount,
        bytes32 crossChainId,
        bytes calldata destWallet,
        uint256 timeoutSec
    ) external {
        if (amount == 0) revert ZeroAmount();
        if (token == address(0)) revert ZeroAddress();
        if (locks[crossChainId].sender != address(0)) revert AlreadyLocked(crossChainId);

        uint256 timeoutAt = block.timestamp + timeoutSec;
        bytes32 nonceHash = keccak256(abi.encodePacked(
            block.chainid, address(this), msg.sender, crossChainId
        ));

        locks[crossChainId] = LockRecord({
            sender:    msg.sender,
            token:     token,
            amount:    amount,
            timeoutAt: timeoutAt,
            committed: false,
            refunded:  false
        });

        if (!IERC20(token).transferFrom(msg.sender, address(this), amount)) revert TransferFailed();
        emit TokenLocked(msg.sender, token, amount, crossChainId, nonceHash, destWallet, timeoutAt);
    }

    // ── Commit (relayer calls after destination confirmed) ────────────────────

    function commitTransfer(bytes32 crossChainId) external onlyRelayer {
        LockRecord storage rec = locks[crossChainId];
        if (rec.sender == address(0)) revert NotLocked(crossChainId);
        if (rec.committed || rec.refunded) revert AlreadyFinalized(crossChainId);

        rec.committed = true;
        emit TransferCommitted(crossChainId);
    }

    // ── Unlock (SOL→ETH reverse flow: relayer releases funds) ────────────────

    function unlock(
        address to,
        address token,
        uint256 amount,
        bytes32 crossChainId
    ) external onlyRelayer {
        if (to == address(0)) revert ZeroAddress();
        if (amount == 0) revert ZeroAmount();
        if (locks[crossChainId].committed || locks[crossChainId].refunded) {
            revert AlreadyFinalized(crossChainId);
        }

        locks[crossChainId].committed = true;
        if (!IERC20(token).transfer(to, amount)) revert TransferFailed();
        emit TransferCommitted(crossChainId);
    }

    // ── Timeout refund ────────────────────────────────────────────────────────

    function claimTimeout(bytes32 crossChainId) external {
        LockRecord storage rec = locks[crossChainId];
        if (rec.sender == address(0)) revert NotLocked(crossChainId);
        if (rec.committed || rec.refunded) revert AlreadyFinalized(crossChainId);
        if (block.timestamp < rec.timeoutAt) revert NotTimedOut(crossChainId);

        rec.refunded = true;
        if (!IERC20(rec.token).transfer(rec.sender, rec.amount)) revert TransferFailed();
        emit TransferRefunded(crossChainId, rec.sender, rec.amount);
    }

    // ── Admin ─────────────────────────────────────────────────────────────────

    function setRelayer(address _relayer) external onlyOwner {
        if (_relayer == address(0)) revert ZeroAddress();
        emit RelayerUpdated(relayer, _relayer);
        relayer = _relayer;
    }
}
